# site settings

title: Allison Elmer
description: Master of Public Policy Candidate, Univeristy of Chicago Harris School of Public Policy Class of 2024
taglong: Master of Public Policy Candidate, Class of 2024
tagshort: she/her
url: https://amelmer.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/amelmer/amelmer.github.io

# author settings

author:
  name: Allison Elmer
  email: amelmer@uchicago.edu
photo: /assets/jpg/headshot1.jpg

# social media links

social:
  #facebook: username
  github: amelmer
  #instagram: username
  linkedin: allison-marie-elmer
  #stackoverflow: 0000000/username
  #twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
